devices:
  - type: arduino
    address: 5
    components:
      - name: encoder
        side: left
        pins: [9,8,7,6]
      - name: encoder
        side: right
        pins: [5,4,3,2]
  - type: arduino
    address: 21
    components:
    - name: motor
      side: left
      pins:
        enable: 2
        direction: [3, 4]
    - name: motor
      side: right
      pins:
        enable: 11
        direction: [9, 10]
